import { createServer } from 'node:http';
import { mkdirSync, existsSync, readFileSync, statfsSync } from 'node:fs';
import { randomBytes, randomUUID, scryptSync, timingSafeEqual } from 'node:crypto';
import { DatabaseSync } from 'node:sqlite';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { URL } from 'node:url';

const execFileAsync = promisify(execFile);
const PORT = Number(process.env.PORT || 8787);
const DATA_DIR = process.env.FOUNDRY_DATA_DIR || new URL('../data/', import.meta.url).pathname;
const DIST_DIR = new URL('../dist/', import.meta.url).pathname;
mkdirSync(DATA_DIR, { recursive: true });
const db = new DatabaseSync(`${DATA_DIR}foundry.sqlite`);
db.exec(`
  PRAGMA foreign_keys = ON;
  CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY, name TEXT NOT NULL, email TEXT UNIQUE NOT NULL, password_hash TEXT NOT NULL, created_at TEXT NOT NULL);
  CREATE TABLE IF NOT EXISTS workspaces (id TEXT PRIMARY KEY, name TEXT NOT NULL, slug TEXT UNIQUE NOT NULL, docs TEXT NOT NULL DEFAULT '{}', settings TEXT NOT NULL DEFAULT '{}', created_at TEXT NOT NULL);
  CREATE TABLE IF NOT EXISTS memberships (user_id TEXT NOT NULL, workspace_id TEXT NOT NULL, role TEXT NOT NULL CHECK(role IN ('owner','admin','editor','viewer')), status TEXT NOT NULL DEFAULT 'active', PRIMARY KEY(user_id, workspace_id), FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE, FOREIGN KEY(workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE);
  CREATE TABLE IF NOT EXISTS sessions (token TEXT PRIMARY KEY, user_id TEXT NOT NULL, expires_at TEXT NOT NULL, FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
  CREATE TABLE IF NOT EXISTS sources (id TEXT PRIMARY KEY, workspace_id TEXT NOT NULL, name TEXT NOT NULL, provider TEXT NOT NULL, repo_url TEXT NOT NULL, branch TEXT NOT NULL DEFAULT 'main', sync_frequency TEXT NOT NULL DEFAULT 'daily', status TEXT NOT NULL DEFAULT 'pending', last_synced_at TEXT, last_error TEXT, created_at TEXT NOT NULL, FOREIGN KEY(workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE);
  CREATE TABLE IF NOT EXISTS sync_jobs (id TEXT PRIMARY KEY, source_id TEXT NOT NULL, status TEXT NOT NULL, started_at TEXT NOT NULL, finished_at TEXT, message TEXT, FOREIGN KEY(source_id) REFERENCES sources(id) ON DELETE CASCADE);
  CREATE TABLE IF NOT EXISTS skills (id TEXT PRIMARY KEY, workspace_id TEXT NOT NULL, source_id TEXT, name TEXT NOT NULL, slug TEXT NOT NULL, description TEXT NOT NULL DEFAULT '', category TEXT NOT NULL DEFAULT 'Uncategorized', author TEXT NOT NULL DEFAULT 'workspace', installs INTEGER NOT NULL DEFAULT 0, tags TEXT NOT NULL DEFAULT '[]', color TEXT NOT NULL DEFAULT 'mint', icon TEXT NOT NULL DEFAULT '✦', source_path TEXT, updated_at TEXT NOT NULL, UNIQUE(workspace_id, slug), FOREIGN KEY(workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE, FOREIGN KEY(source_id) REFERENCES sources(id) ON DELETE SET NULL);
`);

const now = () => new Date().toISOString();
const id = () => randomUUID();
const json = (res, status, payload) => { res.writeHead(status, { 'content-type': 'application/json', 'access-control-allow-origin': 'http://localhost:5173', 'access-control-allow-credentials': 'true', 'access-control-allow-headers': 'content-type, authorization', 'access-control-allow-methods': 'GET,POST,PATCH,DELETE,OPTIONS' }); res.end(JSON.stringify(payload)); };
const readBody = (req) => new Promise((resolve, reject) => { let raw = ''; req.on('data', chunk => { raw += chunk; if (raw.length > 1e6) reject(new Error('Payload too large')); }); req.on('end', () => { try { resolve(raw ? JSON.parse(raw) : {}); } catch { reject(new Error('Invalid JSON')); } }); req.on('error', reject); });
const slugify = (value) => value.toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '') || `workspace-${Date.now()}`;
const hashPassword = (password, salt = randomBytes(16).toString('hex')) => `${salt}:${scryptSync(password, salt, 64).toString('hex')}`;
const verifyPassword = (password, stored) => { const [salt, hash] = stored.split(':'); const a = Buffer.from(hash, 'hex'); const b = scryptSync(password, salt, 64); return a.length === b.length && timingSafeEqual(a, b); };
const getToken = req => (req.headers.authorization || '').startsWith('Bearer ') ? req.headers.authorization.slice(7) : (req.headers.cookie || '').match(/session=([^;]+)/)?.[1];
function currentUser(req) { const token = getToken(req); if (!token) return null; const session = db.prepare('SELECT user_id FROM sessions WHERE token = ? AND expires_at > ?').get(token, now()); if (!session) return null; return db.prepare('SELECT id, name, email, created_at FROM users WHERE id = ?').get(session.user_id); }
function workspaceFor(user) { return user && db.prepare(`SELECT w.*, m.role, m.status FROM workspaces w JOIN memberships m ON m.workspace_id=w.id WHERE m.user_id=? AND m.status='active' ORDER BY w.created_at LIMIT 1`).get(user.id); }
function requireAuth(req, res) { const user = currentUser(req); if (!user) { json(res, 401, { error: 'Authentication required' }); return null; } return user; }
function requireWorkspace(req, res, roles = []) { const user = requireAuth(req, res); if (!user) return null; const workspace = workspaceFor(user); if (!workspace || (roles.length && !roles.includes(workspace.role))) { json(res, 403, { error: 'You do not have access to this workspace action' }); return null; } return { user, workspace }; }
const publicUser = (user, workspace) => ({ user, workspace: { id: workspace.id, name: workspace.name, slug: workspace.slug, role: workspace.role, settings: JSON.parse(workspace.settings), docs: JSON.parse(workspace.docs) } });

async function handle(req, res) {
  if (req.method === 'OPTIONS') return json(res, 204, {});
  const url = new URL(req.url, `http://${req.headers.host || 'localhost'}`);
  const path = url.pathname;
  try {
    if (req.method === 'GET' && path === '/api') return json(res, 200, { service: 'foundry-api', status: 'ok', health: '/api/health', endpoints: ['/api/auth/register', '/api/auth/login', '/api/auth/me', '/api/workspace/settings', '/api/workspace/docs', '/api/workspace/members', '/api/sources', '/api/skills'] });
    if (req.method === 'GET' && !path.startsWith('/api/')) { const asset = path === '/' ? `${DIST_DIR}index.html` : `${DIST_DIR}${path}`; if (existsSync(asset)) { const type = asset.endsWith('.html') ? 'text/html' : asset.endsWith('.js') ? 'text/javascript' : asset.endsWith('.css') ? 'text/css' : 'application/octet-stream'; res.writeHead(200, { 'content-type': type }); return res.end(readFileSync(asset)); } }
    if (req.method === 'POST' && path === '/api/auth/register') {
      const body = await readBody(req); const name = String(body.name || '').trim(); const email = String(body.email || '').trim().toLowerCase(); const password = String(body.password || ''); const workspaceName = String(body.workspaceName || `${name}'s workspace`).trim();
      if (!name || !email || password.length < 8) return json(res, 400, { error: 'Name, email, and a password of at least 8 characters are required' });
      if (db.prepare('SELECT id FROM users WHERE email=?').get(email)) return json(res, 409, { error: 'An account with that email already exists' });
      const userId = id(); const workspaceId = id(); const workspaceSlug = `${slugify(workspaceName)}-${workspaceId.slice(0, 6)}`; const created = now();
      db.exec('BEGIN'); try { db.prepare('INSERT INTO users VALUES (?,?,?,?,?)').run(userId, name, email, hashPassword(password), created); db.prepare('INSERT INTO workspaces VALUES (?,?,?,?,?,?)').run(workspaceId, workspaceName, workspaceSlug, JSON.stringify({ welcome: 'Add your team documentation here.' }), JSON.stringify({ visibility: 'private', allowDirectUpload: true, allowGitSources: true, defaultBranch: 'main' }), created); db.prepare('INSERT INTO memberships VALUES (?,?,?,?)').run(userId, workspaceId, 'owner', 'active'); db.exec('COMMIT'); } catch (error) { db.exec('ROLLBACK'); throw error; }
      const token = randomBytes(32).toString('hex'); db.prepare('INSERT INTO sessions VALUES (?,?,?)').run(token, userId, new Date(Date.now() + 1000 * 60 * 60 * 24 * 30).toISOString()); const workspace = workspaceFor({ id: userId }); res.setHeader('set-cookie', `session=${token}; HttpOnly; SameSite=Lax; Path=/; Max-Age=2592000`); return json(res, 201, publicUser({ id: userId, name, email, created_at: created }, workspace));
    }
    if (req.method === 'POST' && path === '/api/auth/login') { const body = await readBody(req); const user = db.prepare('SELECT * FROM users WHERE email=?').get(String(body.email || '').trim().toLowerCase()); if (!user || !verifyPassword(String(body.password || ''), user.password_hash)) return json(res, 401, { error: 'Invalid email or password' }); const token = randomBytes(32).toString('hex'); db.prepare('INSERT INTO sessions VALUES (?,?,?)').run(token, user.id, new Date(Date.now() + 1000 * 60 * 60 * 24 * 30).toISOString()); const workspace = workspaceFor(user); res.setHeader('set-cookie', `session=${token}; HttpOnly; SameSite=Lax; Path=/; Max-Age=2592000`); return json(res, 200, publicUser({ id: user.id, name: user.name, email: user.email, created_at: user.created_at }, workspace)); }
    if (req.method === 'POST' && path === '/api/auth/logout') { const token = getToken(req); if (token) db.prepare('DELETE FROM sessions WHERE token=?').run(token); res.setHeader('set-cookie', 'session=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0'); return json(res, 200, { ok: true }); }
    if (req.method === 'GET' && path === '/api/auth/me') { const user = requireAuth(req, res); if (!user) return; return json(res, 200, publicUser(user, workspaceFor(user))); }

    if (req.method === 'GET' && path === '/api/workspace/settings') { const ctx = requireWorkspace(req, res); if (!ctx) return; return json(res, 200, JSON.parse(ctx.workspace.settings)); }
    if (req.method === 'PATCH' && path === '/api/workspace/settings') { const ctx = requireWorkspace(req, res, ['owner', 'admin']); if (!ctx) return; const body = await readBody(req); const settings = { ...JSON.parse(ctx.workspace.settings), ...body }; db.prepare('UPDATE workspaces SET settings=? WHERE id=?').run(JSON.stringify(settings), ctx.workspace.id); return json(res, 200, settings); }
    if (req.method === 'GET' && path === '/api/workspace/docs') { const ctx = requireWorkspace(req, res); if (!ctx) return; return json(res, 200, JSON.parse(ctx.workspace.docs)); }
    if (req.method === 'PUT' && path === '/api/workspace/docs') { const ctx = requireWorkspace(req, res, ['owner', 'admin', 'editor']); if (!ctx) return; const body = await readBody(req); db.prepare('UPDATE workspaces SET docs=? WHERE id=?').run(JSON.stringify(body), ctx.workspace.id); return json(res, 200, body); }

    if (req.method === 'GET' && path === '/api/workspace/members') { const ctx = requireWorkspace(req, res); if (!ctx) return; const members = db.prepare(`SELECT u.id,u.name,u.email,m.role,m.status,u.created_at FROM users u JOIN memberships m ON m.user_id=u.id WHERE m.workspace_id=? ORDER BY u.created_at`).all(ctx.workspace.id); return json(res, 200, members); }
    if (req.method === 'POST' && path === '/api/workspace/members/invite') { const ctx = requireWorkspace(req, res, ['owner', 'admin']); if (!ctx) return; const body = await readBody(req); const email = String(body.email || '').trim().toLowerCase(); const role = ['admin', 'editor', 'viewer'].includes(body.role) ? body.role : 'viewer'; const invitee = db.prepare('SELECT id FROM users WHERE email=?').get(email); if (!invitee) return json(res, 404, { error: 'User must register before they can be added in this local build' }); db.prepare('INSERT OR REPLACE INTO memberships VALUES (?,?,?,?)').run(invitee.id, ctx.workspace.id, role, 'active'); return json(res, 201, { ok: true, email, role }); }
    const memberMatch = path.match(/^\/api\/workspace\/members\/([^/]+)$/); if (memberMatch && req.method === 'PATCH') { const ctx = requireWorkspace(req, res, ['owner', 'admin']); if (!ctx) return; const body = await readBody(req); const role = ['admin', 'editor', 'viewer'].includes(body.role) ? body.role : 'viewer'; db.prepare('UPDATE memberships SET role=?, status=? WHERE user_id=? AND workspace_id=?').run(role, body.status === 'suspended' ? 'suspended' : 'active', memberMatch[1], ctx.workspace.id); return json(res, 200, { ok: true }); }
    if (memberMatch && req.method === 'DELETE') { const ctx = requireWorkspace(req, res, ['owner']); if (!ctx) return; db.prepare('DELETE FROM memberships WHERE user_id=? AND workspace_id=?').run(memberMatch[1], ctx.workspace.id); return json(res, 200, { ok: true }); }

    if (req.method === 'GET' && path === '/api/sources') { const ctx = requireWorkspace(req, res); if (!ctx) return; return json(res, 200, db.prepare('SELECT * FROM sources WHERE workspace_id=? ORDER BY created_at DESC').all(ctx.workspace.id)); }
    if (req.method === 'POST' && path === '/api/sources') { const ctx = requireWorkspace(req, res, ['owner', 'admin', 'editor']); if (!ctx) return; const body = await readBody(req); const provider = ['github', 'gitlab', 'bitbucket', 'generic'].includes(String(body.provider).toLowerCase()) ? String(body.provider).toLowerCase() : 'generic'; if (!body.repoUrl) return json(res, 400, { error: 'repoUrl is required' }); const sourceId = id(); db.prepare('INSERT INTO sources VALUES (?,?,?,?,?,?,?,?,?,?,?)').run(sourceId, ctx.workspace.id, body.name || body.repoUrl, provider, body.repoUrl, body.branch || 'main', body.syncFrequency || 'daily', 'pending', null, null, now()); return json(res, 201, db.prepare('SELECT * FROM sources WHERE id=?').get(sourceId)); }
    const sourceMatch = path.match(/^\/api\/sources\/([^/]+)\/sync$/); if (sourceMatch && req.method === 'POST') { const ctx = requireWorkspace(req, res, ['owner', 'admin', 'editor']); if (!ctx) return; const source = db.prepare('SELECT * FROM sources WHERE id=? AND workspace_id=?').get(sourceMatch[1], ctx.workspace.id); if (!source) return json(res, 404, { error: 'Source not found' }); const jobId = id(); db.prepare('INSERT INTO sync_jobs VALUES (?,?,?,?,?,?)').run(jobId, source.id, 'queued', now(), null, null); runSync(source, jobId).catch(() => {}); return json(res, 202, { jobId, status: 'queued' }); }
    if (req.method === 'GET' && path === '/api/skills') { const ctx = requireWorkspace(req, res); if (!ctx) return; const rows = db.prepare('SELECT * FROM skills WHERE workspace_id=? ORDER BY updated_at DESC').all(ctx.workspace.id); return json(res, 200, rows.map(publicSkill)); }
    if (req.method === 'POST' && path === '/api/skills') { const ctx = requireWorkspace(req, res, ['owner', 'admin', 'editor']); if (!ctx) return; const body = await readBody(req); if (!body.name) return json(res, 400, { error: 'name is required' }); const skill = { id: id(), workspace_id: ctx.workspace.id, source_id: null, name: body.name, slug: body.slug || slugify(body.name), description: body.description || '', category: body.category || 'Uncategorized', author: ctx.user.name, installs: 0, tags: JSON.stringify(Array.isArray(body.tags) ? body.tags : []), color: body.color || 'mint', icon: body.icon || '✦', source_path: null, updated_at: now() }; db.prepare('INSERT INTO skills VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(...Object.values(skill)); return json(res, 201, publicSkill(db.prepare('SELECT * FROM skills WHERE id=?').get(skill.id))); }
    const sourceDeleteMatch = path.match(/^\/api\/sources\/([^/]+)$/); if (sourceDeleteMatch && req.method === 'DELETE') { const ctx = requireWorkspace(req, res, ['owner', 'admin', 'editor']); if (!ctx) return; const source = db.prepare('SELECT id FROM sources WHERE id=? AND workspace_id=?').get(sourceDeleteMatch[1], ctx.workspace.id); if (!source) return json(res, 404, { error: 'Source not found' }); db.prepare('DELETE FROM sources WHERE id=?').run(source.id); return json(res, 200, { ok: true }); }
    if (req.method === 'GET' && path === '/api/health') return json(res, 200, { ok: true, service: 'foundry-api', time: now() });
    if (req.method === 'GET' && path === '/api/system/storage') { const user = requireAuth(req, res); if (!user) return; const stats = statfsSync(DATA_DIR); const total = Number(stats.blocks) * Number(stats.bsize); const free = Number(stats.bfree) * Number(stats.bsize); return json(res, 200, { totalBytes: total, freeBytes: free, usedBytes: Math.max(0, total - free), mount: DATA_DIR }); }
    return json(res, 404, { error: 'Not found' });
  } catch (error) { console.error(error); return json(res, 500, { error: 'Internal server error' }); }
}

async function runSync(source, jobId) {
  db.prepare('UPDATE sync_jobs SET status=?, message=? WHERE id=?').run('running', 'Fetching repository', jobId); db.prepare('UPDATE sources SET status=?, last_error=NULL WHERE id=?').run('syncing', source.id);
  try { const target = `${DATA_DIR}sync-${source.id}`; const args = existsSync(target) ? ['-C', target, 'pull', '--ff-only'] : ['clone', '--depth', '1', '--branch', source.branch, source.repo_url, target]; await execFileAsync('git', args, { timeout: 120000 }); indexSkillsFromRepo(source, target); db.prepare('UPDATE sources SET status=?, last_synced_at=? WHERE id=?').run('synced', now(), source.id); db.prepare('UPDATE sync_jobs SET status=?, finished_at=?, message=? WHERE id=?').run('completed', now(), 'Repository fetched and skills indexed', jobId); } catch (error) { db.prepare('UPDATE sources SET status=?, last_error=? WHERE id=?').run('error', error.message.slice(0, 500), source.id); db.prepare('UPDATE sync_jobs SET status=?, finished_at=?, message=? WHERE id=?').run('failed', now(), error.message.slice(0, 500), jobId); }
}

const publicSkill = row => ({ ...row, tags: JSON.parse(row.tags || '[]') });
async function indexSkillsFromRepo(source, target) { const { stdout } = await execFileAsync('find', [target, '-name', 'SKILL.md', '-type', 'f'], { timeout: 30000 }); for (const file of stdout.split('\n').filter(Boolean)) { const text = (await import('node:fs/promises')).readFile(file, 'utf8'); const content = await text; const frontmatter = content.match(/^---\n([\s\S]*?)\n---/); const values = {}; if (frontmatter) frontmatter[1].split('\n').forEach(line => { const match = line.match(/^([\w-]+):\s*["']?(.+?)["']?\s*$/); if (match) values[match[1]] = match[2]; }); const name = values.name || file.split('/').at(-2) || 'Untitled skill'; const skill = { id: id(), workspace_id: source.workspace_id, source_id: source.id, name, slug: slugify(name), description: values.description || content.replace(/^---[\s\S]*?---/, '').trim().split('\n').find(Boolean) || '', category: values.category || 'Uncategorized', author: values.author || source.provider, installs: 0, tags: JSON.stringify(String(values.tags || '').split(',').map(tag => tag.trim()).filter(Boolean)), color: 'mint', icon: '✦', source_path: file.slice(target.length + 1), updated_at: now() }; db.prepare('INSERT INTO skills VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(workspace_id,slug) DO UPDATE SET source_id=excluded.source_id, description=excluded.description, category=excluded.category, author=excluded.author, tags=excluded.tags, source_path=excluded.source_path, updated_at=excluded.updated_at').run(...Object.values(skill)); } }

createServer(handle).listen(PORT, '0.0.0.0', () => console.log(`Foundry API listening on http://localhost:${PORT}`));
